### ISSUE TITLE
게시글 상세 조회 응답 데이터 수정

### ISSUE THREAD

**Issue by NuhGnod** [re-Duck/reDuck-server#107]
게시글 상세 조회 시, comments 데이터 삭제 필요. (댓글 조회 api분리됨)

**Comment by Im-younique** [comment]
유저 팔로워 채택수 포함

**Comment by NuhGnod** [comment]
- [] 채택 수
- [x] 팔로워 수
- [x] 스크랩
- [x] 좋아요
