### ISSUE TITLE
User 도메인 파트 부족한 기능 보완

### ISSUE THREAD

**Issue by NuhGnod** [re-Duck/reDuck-server#6]
회원가입
- [x] 프로필 이미지 없이 회원가입 못하는 이슈 발생
- [x] 회원정보에 대한 require 부여
- [x] 세부적인 예외처리
- [x] 마이페이지 개인정보 변경
- [x] #17
- [x] 개발연차 로직 수정
- [x] 회원탈퇴
- [x] 로그아웃

**Comment by DongYounYim** [comment]
회원가입시 기본 메일 인증 (인증코드 발급)
1. 메일 입력 후 메일 request 시 인증 코드 담긴 메일 전송 및 인증 코드 client 단에 응답.
2. 인증 번호 입력 후 확인 시 client 단에서 체크
=> 회원가입 가능
c.f. 인증 번호 재 발급 요청 시에도 같은 과정으로 진행

이 후, 학교 메일 / 직장 메일 인증은 회원 가입 후 다음 탭에서 진행 혹은 마이페이지에서 진행 가능
=> 인증될 시 인증 뱃지를 보여주거나, 인증되어야 학교 / 직장 명 표기로 로직 설정
c.f. 학교 / 직장 메일은 인증 플래그를 둔다.
